namespace: /nuclei

roc-alice:
  defines: runnable
  inherits: ./rococo
  variables:
    node-name: roc-alice
    cmds: "--alice --node-key 0000000000000000000000000000000000000000000000000000000000000001"

roc-bob:
  defines: runnable
  inherits: ./rococo
  variables:
    node-name: roc-bob
    cmds: <- "--bob --bootnodes /dns/" get-hostname("nuclei/roc-alice", "node") "/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp" concat-all

roc-monitoring-prometheus:
  defines: runnable
  inherits: ./prometheus
  variables:
    target-nodes: <- get-hostname("nuclei/roc-alice", "node") `:${node-port}` " " get-hostname("nuclei/roc-bob", "node") `:${node-port}` concat-all

roc-monitoring-grafana:
  defines: runnable
  inherits: ./grafana
  variables:
    prometheus-endpoint: <- "http://" get-hostname("nuclei/roc-monitoring-prometheus", "prometheus") ":9090" concat-all

roc:
  defines: process-group
  runnable-list:
    - nuclei/roc-alice
    - nuclei/roc-bob
    - nuclei/roc-monitoring-prometheus
    - nuclei/roc-monitoring-grafana

roc-alice-local:
  defines: runnable
  inherits: ./roc-alice

roc-bob-local:
  defines: runnable
  inherits: ./roc-bob
  variables:
    wsrpc-port: 9945
    p2p-port: 30334
    prometheus-port: 9616
    cmds: <- "--bob --bootnodes /dns/" get-hostname("nuclei/roc-alice-local", "node") "/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp" concat-all

roc-local:
  defines: process-group
  runnable-list:
    - nuclei/roc-alice-local
    - nuclei/roc-bob-local
    - nuclei/roc-monitoring-prometheus
    - nuclei/roc-monitoring-grafana
